$issues = @(
    @{ title='Security: Unrestricted GitHub Issue Creation in /api/issues/create'; body='The /api/issues/create endpoint lacks repository ownership validation, allowing any authenticated user to create issues on arbitrary GitHub repositories on behalf of the configured GITHUB_PAT account.'; label='security' },
    @{ title='Security: Missing Rate Limiter on /api/issues/create'; body='The /api/issues/create endpoint lacks rate limiting, making it susceptible to spam and GitHub API rate-limit exhaustion attacks.'; label='security' },
    @{ title='Security: Missing Rate Limiter on Report Export Endpoints'; body='The /api/reports/html and /api/reports/pdf endpoints have no rate limiters, making the server vulnerable to Denial of Service via repeated complex PDF/HTML generation.'; label='security' },
    @{ title='Bug: Memory Leak in Session Contexts (repoContexts)'; body='The backend stores repoContexts (containing all cloned files) in memory for 30 minutes. This unbounded in-memory storage can lead to an Out Of Memory (OOM) crash if a user repeatedly analyzes large repositories.'; label='bug' },
    @{ title='Security: simpleGit.clone is Vulnerable to Disk Exhaustion'; body='The maxRepoSizeMB check is performed *after* the Git clone finishes. A malicious user can provide a repository containing a massive zip bomb, exhausting server disk space and crashing the Node.js server before the size check triggers.'; label='security' },
    @{ title='Bug: Webhook Processing Queue Memory Loss on Restart'; body='The reviewQueues Map stores pending pull request review tasks in memory. If the Node.js server crashes or restarts, all queued PR reviews are permanently lost.'; label='bug' },
    @{ title='Security: RAG Cleanup Endpoints are Unauthenticated'; body='The FastAPI endpoints /api/rag/cleanup and /api/rag/delete-vectors are completely public. A malicious actor can call these endpoints to delete arbitrary RAG chunks from the ChromaDB vector store.'; label='security' },
    @{ title='Security: systemPrompt Injection Bypass via Chat API'; body='While the /api/analyze endpoint strictly validates systemPrompt for homoglyphs and dangerous directives, the /api/chat endpoint passes systemPrompt directly to the AI engine without any validation, allowing a bypass.'; label='security' },
    @{ title='Security: CSS Sanitizer Allows Malicious Data URIs'; body='The css_sanitizer allows the background property but does not strictly filter out malicious url(data:text/html...) payloads, potentially leading to XSS vulnerabilities when generating reports.'; label='security' },
    @{ title='Bug: ChatRequest Model Ignores systemPrompt'; body='In ai-engine/app.py, the user-provided systemPrompt in the /chat route is completely ignored and overwritten with a hardcoded RepoSage Chat system prompt.'; label='bug' },
    @{ title='Enhancement: Lack of Concurrency in Groq Batched API Calls'; body='The AI engine processes file batches sequentially (for idx, batch in enumerate(batches)). This leads to very slow response times for large repositories. We should implement asyncio.gather for parallel processing.'; label='enhancement' },
    @{ title='Bug: Silent Failure on Partial Batch Processing'; body='If the first batch in the AI engine fails, it raises an HTTP exception, but if subsequent batches fail, they are silently skipped. The API should return a partial success indicator to the frontend so the user knows some files were not analyzed.'; label='bug' },
    @{ title='Enhancement: No File Size Limit on RAG Split Endpoints'; body='Passing arbitrarily large files/strings to the text_splitter endpoint could cause process starvation and memory bloat in the FastAPI engine.'; label='enhancement' },
    @{ title='Bug: Missing Error Boundary for Markdown Renderer'; body='If ReactMarkdown fails to parse a malformed AI response in the frontend, it crashes the entire chat/review UI. An ErrorBoundary should be wrapped around the markdown components.'; label='bug' },
    @{ title='Enhancement: No Auto-Scroll to Bottom on Chat Stream'; body='The frontend chat UI does not automatically scroll down as new AI messages stream in or generate, requiring manual scrolling by the user.'; label='enhancement' },
    @{ title='Enhancement: Lack of ARIA labels on Code Block Action Buttons'; body='The Copy and Download buttons on generated code blocks lack proper aria-label attributes, creating an accessibility issue for screen readers.'; label='enhancement' },
    @{ title='Performance: Inefficient Re-rendering of Review Findings Tree'; body='Expanding or collapsing folders in the review results causes a full component tree re-render, resulting in lag on large repositories.'; label='enhancement' },
    @{ title='Bug: Hardcoded API URLs in Production Builds Break Gracefully'; body='If VITE_API_URL is omitted, the frontend breaks completely instead of gracefully showing a misconfiguration error state or falling back to a relative path.'; label='bug' },
    @{ title='Enhancement: Export PDF/HTML Feature Lacks Loading State'; body='When generating a large PDF/HTML report, the UI freezes or appears unresponsive because it lacks a loading spinner and is not offloaded to a Web Worker.'; label='enhancement' },
    @{ title='Enhancement: Missing Pagination in Vector Store API'; body='If endpoints are added or utilized to retrieve vectors from ChromaDB, they load everything into memory. RAG endpoints should support cursor-based pagination.'; label='enhancement' }
)

foreach ($issue in $issues) {
    gh issue create --title $issue.title --body $issue.body --label $issue.label
    Start-Sleep -Seconds 1
}
