"""
services/vector_store.py
~~~~~~~~~~~~~~~~~~~~~~~~
Ephemeral, per-review-session ChromaDB vector store for the AST chunking
pipeline in the RepoSage AI Engine.

Design decisions
----------------
- Uses ``chromadb.EphemeralClient`` (in-memory) rather than the persistent
  client in ``rag.py``.  This means each review invocation starts with a
  clean slate — no filesystem side effects, no collection name collisions,
  and no state leaking between unrelated reviews.
- Embeddings are generated by the existing ``embeddings.embed_texts``
  function so the entire system uses a single embedding model path.
- The existing ``rag.py`` (PersistentClient) is completely untouched.
  Both modules coexist without conflict.

Public API
----------
store_chunks(chunks, collection_name) -> int
    Embed and store a list of chunk dicts (as returned by ast_chunker).
    Returns the number of items stored.

retrieve_top_k(query, collection_name, k=5) -> list[dict]
    Run a semantic similarity query and return the top-k matching chunks.
    Returns [] when the collection is empty or query is blank.

clear_collection(collection_name) -> None
    Delete all documents from the named collection.  Call at the end of a
    review session to release memory.
"""

from __future__ import annotations

import hashlib
import threading
from typing import Optional

import chromadb
from chromadb.config import Settings

from embeddings import embed_texts

# ---------------------------------------------------------------------------
# Module-level EphemeralClient — one per process, shared across review calls.
# EphemeralClient is thread-safe in ChromaDB ≥ 0.4.
# ---------------------------------------------------------------------------
_client_lock = threading.Lock()
_client: Optional[chromadb.ClientAPI] = None


def _get_client() -> chromadb.ClientAPI:
    """Lazy-initialise a module-level EphemeralClient (in-memory)."""
    global _client
    if _client is None:
        with _client_lock:
            if _client is None:
                _client = chromadb.EphemeralClient(
                    settings=Settings(anonymized_telemetry=False)
                )
    return _client


def _get_collection(collection_name: str):
    """Return (or create) the named collection on the ephemeral client."""
    client = _get_client()
    return client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},
    )


def _safe_collection_name(name: str) -> str:
    """
    ChromaDB collection names must be 3-63 chars, alphanumeric + hyphens,
    no leading/trailing hyphens.  Hash long or special names.
    """
    # Replace non-alphanumeric (except hyphens) with hyphens
    sanitised = "".join(c if c.isalnum() or c == "-" else "-" for c in name)
    # Trim leading/trailing hyphens
    sanitised = sanitised.strip("-")
    if len(sanitised) < 3 or len(sanitised) > 63:
        sanitised = "rag-" + hashlib.sha256(name.encode()).hexdigest()[:16]
    return sanitised


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def store_chunks(
    chunks: list[dict],
    collection_name: str = "ast-review-session",
) -> int:
    """
    Embed and upsert *chunks* into the ephemeral ChromaDB collection.

    Parameters
    ----------
    chunks : list[dict]
        Each dict must have ``"chunk_id"`` (str), ``"content"`` (str) and
        ``"metadata"`` (dict).  This matches the output of
        ``services.ast_chunker.chunk_code``.
    collection_name : str
        Logical name for the collection.  Will be sanitised automatically.

    Returns
    -------
    int
        Number of chunks stored (0 if *chunks* is empty).
    """
    if not chunks:
        return 0

    safe_name = _safe_collection_name(collection_name)
    collection = _get_collection(safe_name)

    documents = [c["content"] for c in chunks]
    ids = [c["chunk_id"] for c in chunks]
    # Sanitise metadata: ChromaDB requires all values to be str/int/float/bool.
    metadatas = []
    for c in chunks:
        raw_meta = c.get("metadata", {})
        clean_meta = {
            k: (v if isinstance(v, (str, int, float, bool)) else str(v))
            for k, v in raw_meta.items()
        }
        metadatas.append(clean_meta)

    embeddings = embed_texts(documents)

    collection.upsert(
        documents=documents,
        embeddings=embeddings,
        metadatas=metadatas,
        ids=ids,
    )
    return len(chunks)


def retrieve_top_k(
    query: str,
    collection_name: str = "ast-review-session",
    k: int = 5,
) -> list[dict]:
    """
    Retrieve the top-*k* semantically similar chunks for *query*.

    Parameters
    ----------
    query : str
        The search text (e.g. a diff hunk or a code snippet).
    collection_name : str
        Must match the name used in ``store_chunks``.
    k : int
        Maximum number of results to return.

    Returns
    -------
    list[dict]
        Each dict has ``"chunk_id"``, ``"content"``, ``"metadata"``, and
        ``"similarity_score"`` keys.  Returns ``[]`` if the collection is
        empty or *query* is blank.
    """
    if not query or not query.strip():
        return []

    safe_name = _safe_collection_name(collection_name)
    collection = _get_collection(safe_name)

    count = collection.count()
    if count == 0:
        return []

    n = min(k, count)
    query_embedding = embed_texts([query])

    results = collection.query(
        query_embeddings=query_embedding,
        n_results=n,
    )

    documents  = results.get("documents",  [[]])[0]
    metadatas  = results.get("metadatas",  [[]])[0]
    distances  = results.get("distances",  [[]])[0]
    ids        = results.get("ids",        [[]])[0]

    output: list[dict] = []
    for i, doc in enumerate(documents):
        output.append({
            "chunk_id":        ids[i] if i < len(ids) else None,
            "content":         doc,
            "metadata":        metadatas[i] if i < len(metadatas) else {},
            "similarity_score": 1.0 - distances[i] if i < len(distances) else None,
        })
    return output


def clear_collection(collection_name: str = "ast-review-session") -> None:
    """
    Remove all documents from *collection_name*.

    This is a best-effort cleanup call at the end of a review session.
    It does NOT delete the collection object itself (which is cheap to keep).
    """
    safe_name = _safe_collection_name(collection_name)
    client = _get_client()
    try:
        collection = client.get_collection(safe_name)
        batch_size = 500
        while True:
            result = collection.get(limit=batch_size, include=[])
            ids = result.get("ids", [])
            if not ids:
                break
            collection.delete(ids=ids)
    except Exception:
        # Collection may not exist yet — that's fine.
        pass
